package data.entities;

import data.annotations.Display;
import jakarta.persistence.*;

/**
 * Represents a Book entity in the system.
 * This class is mapped to the "book" table in the database,
 * which stores information about books in the library.
 */
@Entity
@Table(name = "book")
public class Book {

    /**
     * The unique ID of the book.
     * This field is auto-generated by the database.
     */
    @Display
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The title of the book.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String title;

    /**
     * The author of the book.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String author;

    /**
     * The publisher of the book.
     * This is a many-to-one relationship with the "Publisher" entity.
     * The "publisherId" column in the "book" table is used to link to the publisher.
     * This field cannot be null.
     */
    @Display
    @ManyToOne
    @JoinColumn(name = "publisherId", nullable = false)
    private Publisher publisher;

    /**
     * The year the book was published.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private int publicationYear;

    /**
     * The ISBN (International Standard Book Number) of the book.
     * This field cannot be null and must be unique.
     */
    @Display
    @Column(nullable = false, unique = true)
    private String isbn;

    /**
     * Retrieves the unique ID of the book.
     *
     * @return The ID of the book.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the book.
     *
     * @param id The ID to set for the book.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Retrieves the title of the book.
     *
     * @return The title of the book.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the book.
     *
     * @param title The title to set for the book.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Retrieves the author of the book.
     *
     * @return The author of the book.
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the author of the book.
     *
     * @param author The author to set for the book.
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Retrieves the publisher of the book.
     *
     * @return The publisher of the book.
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the publisher of the book.
     *
     * @param publisher The publisher to set for the book.
     */
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    /**
     * Retrieves the publication year of the book.
     *
     * @return The publication year of the book.
     */
    public int getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the publication year of the book.
     *
     * @param publicationYear The publication year to set for the book.
     */
    public void setPublicationYear(int publicationYear) {
        this.publicationYear = publicationYear;
    }

    /**
     * Retrieves the ISBN of the book.
     *
     * @return The ISBN of the book.
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the ISBN of the book.
     *
     * @param isbn The ISBN to set for the book.
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Returns a string representation of the book.
     * This implementation returns the book's ID as a string.
     *
     * @return A string representation of the book.
     */
    @Override
    public String toString() {
        return String.valueOf(id);
    }
}