package data.entities;

import data.annotations.Display;
import jakarta.persistence.*;

import java.util.Date;

/**
 * Represents a Borrowing entity in the system.
 * This class is mapped to the "borrowing" table in the database,
 * which stores information about book borrowings.
 */
@Entity
@Table(name = "borrowing")
public class Borrowing {

    /**
     * The unique ID of the borrowing.
     * This field is auto-generated by the database.
     */
    @Display
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The member who borrowed the book.
     * This is a many-to-one relationship with the "Member" entity.
     * The "MEMBERID" column in the "borrowing" table is used to link to the member.
     * This field cannot be null.
     */
    @Display
    @ManyToOne
    @JoinColumn(name = "MEMBERID", nullable = false)
    private Member member;

    /**
     * The copy of the book that was borrowed.
     * This is a many-to-one relationship with the "Copy" entity.
     * The "COPYID" column in the "borrowing" table is used to link to the copy.
     * This field cannot be null.
     */
    @Display
    @ManyToOne
    @JoinColumn(name = "COPYID", nullable = false)
    private Copy copy;

    /**
     * The date when the book was borrowed.
     * This field cannot be null.
     */
    @Display
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date borrowDate;

    /**
     * The date when the book is expected to be returned.
     * This field is nullable, as it may not be set if the book has not been returned yet.
     */
    @Display
    @Temporal(TemporalType.DATE)
    private Date returnDate;

    /**
     * Retrieves the unique ID of the borrowing.
     *
     * @return The ID of the borrowing.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the borrowing.
     *
     * @param id The ID to set for the borrowing.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Retrieves the member who borrowed the book.
     *
     * @return The member who borrowed the book.
     */
    public Member getMember() {
        return member;
    }

    /**
     * Sets the member who borrowed the book.
     *
     * @param member The member who borrowed the book.
     */
    public void setMember(Member member) {
        this.member = member;
    }

    /**
     * Retrieves the copy of the book that was borrowed.
     *
     * @return The copy of the book that was borrowed.
     */
    public Copy getCopy() {
        return copy;
    }

    /**
     * Sets the copy of the book that was borrowed.
     *
     * @param copy The copy of the book that was borrowed.
     */
    public void setCopy(Copy copy) {
        this.copy = copy;
    }

    /**
     * Retrieves the date when the book was borrowed.
     *
     * @return The borrow date.
     */
    public Date getBorrowDate() {
        return borrowDate;
    }

    /**
     * Sets the date when the book was borrowed.
     *
     * @param borrowDate The date when the book was borrowed.
     */
    public void setBorrowDate(Date borrowDate) {
        this.borrowDate = borrowDate;
    }

    /**
     * Retrieves the date when the book is expected to be returned.
     *
     * @return The return date, or null if not yet set.
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * Sets the date when the book is expected to be returned.
     *
     * @param returnDate The date when the book is expected to be returned.
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * Returns a string representation of the borrowing.
     * This implementation returns the borrowing's ID as a string.
     *
     * @return A string representation of the borrowing.
     */
    @Override
    public String toString() {
        return String.valueOf(id);
    }
}