package data.entities;

import data.annotations.Display;
import jakarta.persistence.*;

/**
 * Represents a Copy entity in the system.
 * This class is mapped to the "copy" table in the database.
 */
@Entity
@Table(name = "copy")
public class Copy {

    /**
     * The unique ID of the copy.
     * This field is auto-generated by the database.
     */
    @Display
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The book associated with the copy.
     * This is a many-to-one relationship with the "Book" entity.
     * The "bookId" column in the "copy" table is used to link to the book.
     * This field cannot be null.
     */
    @Display
    @ManyToOne
    @JoinColumn(name = "bookId", nullable = false)
    private Book book;

    /**
     * The copy number of the book.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private int copyNumber;

    /**
     * The status of the copy (e.g., available, borrowed, damaged).
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String status;

    /**
     * Retrieves the unique ID of the copy.
     *
     * @return The ID of the copy.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the copy.
     *
     * @param id The ID to set for the copy.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Retrieves the book associated with the copy.
     *
     * @return The book associated with the copy.
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the book associated with the copy.
     *
     * @param book The book to associate with the copy.
     */
    public void setBook(Book book) {
        this.book = book;
    }

    /**
     * Retrieves the copy number of the book.
     *
     * @return The copy number of the book.
     */
    public int getCopyNumber() {
        return copyNumber;
    }

    /**
     * Sets the copy number of the book.
     *
     * @param copyNumber The copy number to set for the copy.
     */
    public void setCopyNumber(int copyNumber) {
        this.copyNumber = copyNumber;
    }

    /**
     * Retrieves the status of the copy.
     *
     * @return The status of the copy.
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the status of the copy.
     *
     * @param status The status to set for the copy (e.g., available, borrowed, damaged).
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Returns a string representation of the copy.
     * This implementation returns the copy's ID as a string.
     *
     * @return A string representation of the copy.
     */
    @Override
    public String toString() {
        return String.valueOf(id);
    }
}