package data.entities;

import data.annotations.Display;
import jakarta.persistence.*;

import java.util.Date;

/**
 * Represents a Librarian entity in the system.
 * This class is mapped to the "librarian" table in the database.
 */
@Entity
@Table(name = "librarian")
public class Librarian {

    /**
     * The unique ID of the librarian.
     * This field is auto-generated by the database.
     */
    @Display
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The member associated with the librarian.
     * This is a one-to-one relationship with the "Member" entity.
     * The "memberId" column in the "librarian" table is used to link to the member.
     * This field cannot be null.
     */
    @Display
    @OneToOne
    @JoinColumn(name = "memberId", nullable = false)
    private Member member;

    /**
     * The employment date of the librarian.
     * This field cannot be null.
     */
    @Display
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date employmentDate;

    /**
     * The position of the librarian within the organization.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String position;

    /**
     * Retrieves the unique ID of the librarian.
     *
     * @return The ID of the librarian.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the librarian.
     *
     * @param id The ID to set for the librarian.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Retrieves the member associated with the librarian.
     *
     * @return The member associated with the librarian.
     */
    public Member getMember() {
        return member;
    }

    /**
     * Sets the member associated with the librarian.
     *
     * @param member The member to associate with the librarian.
     */
    public void setMember(Member member) {
        this.member = member;
    }

    /**
     * Retrieves the employment date of the librarian.
     *
     * @return The employment date of the librarian.
     */
    public Date getEmploymentDate() {
        return employmentDate;
    }

    /**
     * Sets the employment date of the librarian.
     *
     * @param employmentDate The employment date to set for the librarian.
     */
    public void setEmploymentDate(Date employmentDate) {
        this.employmentDate = employmentDate;
    }

    /**
     * Retrieves the position of the librarian.
     *
     * @return The position of the librarian.
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the position of the librarian.
     *
     * @param position The position to set for the librarian.
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * Returns a string representation of the librarian.
     * This implementation returns the librarian's ID as a string.
     *
     * @return A string representation of the librarian.
     */
    @Override
    public String toString() {
        return String.valueOf(id);
    }
}