package data.entities;

import data.annotations.Display;
import data.annotations.MatchPattern;
import jakarta.persistence.*;

/**
 * Represents a Member entity in the system.
 * This class is mapped to the "Member" table in the database.
 */
@Entity
@Table(name = "Member")
public class Member {

    /**
     * The unique ID of the member.
     * This field is auto-generated by the database.
     */
    @Display
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the member.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String name;

    /**
     * The email address of the member.
     * This field cannot be null and must be unique.
     */
    @Display
    @MatchPattern(value = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The phone number of the member.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String phoneNumber;

    /**
     * The address of the member.
     * This field cannot be null.
     */
    @Display
    @Column(nullable = false)
    private String address;

    /**
     * Retrieves the unique ID of the member.
     *
     * @return The ID of the member.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the member.
     *
     * @param id The ID to set for the member.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Retrieves the name of the member.
     *
     * @return The name of the member.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the member.
     *
     * @param name The name to set for the member.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Retrieves the email address of the member.
     *
     * @return The email address of the member.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the member.
     *
     * @param email The email to set for the member.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Retrieves the phone number of the member.
     *
     * @return The phone number of the member.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the phone number of the member.
     *
     * @param phoneNumber The phone number to set for the member.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Retrieves the address of the member.
     *
     * @return The address of the member.
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the address of the member.
     *
     * @param address The address to set for the member.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Returns a string representation of the member.
     * This implementation returns the member's ID as a string.
     *
     * @return A string representation of the member.
     */
    @Override
    public String toString() {
        return String.valueOf(id);
    }
}